-- ============================================================================
-- V1 — Baseline do schema (Fases 1 a 4).
--
-- Este arquivo representa o schema COMO ELE JÁ EXISTE na instância Supabase,
-- montado incrementalmente por `spring.jpa.hibernate.ddl-auto=update` ao longo
-- das Fases 1-4. Nessa instância o Flyway NÃO roda este script: `baseline-on-migrate`
-- carimba a base como V1 e parte para a V2.
--
-- Em um banco vazio (CI, ambiente novo, dev local limpo) este é o ponto de partida.
-- Tipos espelham as anotações JPA das entidades:
--   Long -> bigint | String -> varchar(255) | String(n) -> varchar(n)
--   columnDefinition="TEXT" -> text | LocalDate -> date | LocalDateTime -> timestamp
--   enum @Enumerated(STRING) -> varchar(20) | BigDecimal(10,2) -> numeric(10,2)
-- ============================================================================

CREATE TABLE condominios (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              VARCHAR(255)  NOT NULL,
    cnpj              VARCHAR(255)  NOT NULL UNIQUE,
    endereco          VARCHAR(500)  NOT NULL,
    telefone          VARCHAR(255),
    logo_url          VARCHAR(500),
    plano             VARCHAR(255)  NOT NULL DEFAULT 'TRIAL',
    ativo             BOOLEAN       NOT NULL DEFAULT TRUE,
    notifica_email    BOOLEAN       NOT NULL DEFAULT TRUE,
    notifica_whatsapp BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP     NOT NULL,
    updated_at        TIMESTAMP     NOT NULL
);

CREATE TABLE unidades (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bloco         VARCHAR(10),
    numero        VARCHAR(10)  NOT NULL,
    condominio_id BIGINT       NOT NULL REFERENCES condominios (id),
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uk_unidades_condominio_bloco_numero UNIQUE (condominio_id, bloco, numero)
);
CREATE INDEX idx_unidades_condominio ON unidades (condominio_id);

CREATE TABLE usuarios (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL UNIQUE,
    senha           VARCHAR(500) NOT NULL,
    telefone        VARCHAR(255),
    role            VARCHAR(20)  NOT NULL,
    ativo           BOOLEAN      NOT NULL DEFAULT TRUE,
    token_convite   VARCHAR(255) UNIQUE,
    token_expiracao TIMESTAMP,
    condominio_id   BIGINT       NOT NULL REFERENCES condominios (id),
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL
);
CREATE INDEX idx_usuarios_condominio ON usuarios (condominio_id);

CREATE TABLE morador_unidades (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo        VARCHAR(20) NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
    data_inicio TIMESTAMP   NOT NULL,
    data_fim    TIMESTAMP,
    usuario_id  BIGINT      NOT NULL REFERENCES usuarios (id),
    unidade_id  BIGINT      NOT NULL REFERENCES unidades (id),
    created_at  TIMESTAMP   NOT NULL,
    updated_at  TIMESTAMP   NOT NULL,
    CONSTRAINT uk_morador_unidades_usuario_unidade UNIQUE (usuario_id, unidade_id)
);
CREATE INDEX idx_morador_unidades_usuario ON morador_unidades (usuario_id);
CREATE INDEX idx_morador_unidades_unidade ON morador_unidades (unidade_id);

CREATE TABLE areas_comuns (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             VARCHAR(255)   NOT NULL,
    descricao        TEXT,
    capacidade       INTEGER,
    taxa             NUMERIC(10, 2) NOT NULL DEFAULT 0,
    requer_aprovacao BOOLEAN        NOT NULL DEFAULT FALSE,
    ativa            BOOLEAN        NOT NULL DEFAULT TRUE,
    foto_url         VARCHAR(500),
    horario_inicio   VARCHAR(5)     NOT NULL,
    horario_fim      VARCHAR(5)     NOT NULL,
    antecedencia_min INTEGER        NOT NULL DEFAULT 1,
    antecedencia_max INTEGER        NOT NULL DEFAULT 30,
    limite_mensal    INTEGER,
    condominio_id    BIGINT         NOT NULL REFERENCES condominios (id),
    created_at       TIMESTAMP      NOT NULL,
    updated_at       TIMESTAMP      NOT NULL
);
CREATE INDEX idx_areas_comuns_condominio ON areas_comuns (condominio_id);

CREATE TABLE reservas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data        DATE        NOT NULL,
    hora_inicio VARCHAR(5)  NOT NULL,
    hora_fim    VARCHAR(5)  NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    observacao  TEXT,
    area_id     BIGINT      NOT NULL REFERENCES areas_comuns (id),
    usuario_id  BIGINT      NOT NULL REFERENCES usuarios (id),
    unidade_id  BIGINT      NOT NULL REFERENCES unidades (id),
    created_at  TIMESTAMP   NOT NULL,
    updated_at  TIMESTAMP   NOT NULL
);
CREATE INDEX idx_reservas_area ON reservas (area_id);
CREATE INDEX idx_reservas_usuario ON reservas (usuario_id);
CREATE INDEX idx_reservas_area_data ON reservas (area_id, data);

CREATE TABLE pagamentos (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor             NUMERIC(10, 2) NOT NULL,
    status            VARCHAR(20)    NOT NULL DEFAULT 'AGUARDANDO',
    metodo_pagamento  VARCHAR(20)    NOT NULL DEFAULT 'PIX',
    mp_payment_id     VARCHAR(255)   UNIQUE,
    mp_qr_code        TEXT,
    mp_qr_code_base64 TEXT,
    mp_ticket_url     VARCHAR(500),
    paid_at           TIMESTAMP,
    reserva_id        BIGINT         NOT NULL UNIQUE REFERENCES reservas (id),
    created_at        TIMESTAMP      NOT NULL,
    updated_at        TIMESTAMP      NOT NULL
);

CREATE TABLE avisos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo        VARCHAR(255) NOT NULL,
    conteudo      TEXT         NOT NULL,
    anexo_url     VARCHAR(500),
    publicado     BOOLEAN      NOT NULL DEFAULT TRUE,
    destinatario  VARCHAR(20),
    condominio_id BIGINT       NOT NULL REFERENCES condominios (id),
    autor_id      BIGINT       NOT NULL REFERENCES usuarios (id),
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL
);
CREATE INDEX idx_avisos_condominio ON avisos (condominio_id);

CREATE TABLE aviso_leituras (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lido       BOOLEAN   NOT NULL DEFAULT TRUE,
    lido_em    TIMESTAMP NOT NULL,
    aviso_id   BIGINT    NOT NULL REFERENCES avisos (id),
    usuario_id BIGINT    NOT NULL,
    CONSTRAINT uk_aviso_leituras_aviso_usuario UNIQUE (aviso_id, usuario_id)
);
CREATE INDEX idx_aviso_leituras_usuario ON aviso_leituras (usuario_id);

CREATE TABLE faqs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pergunta      TEXT        NOT NULL,
    resposta      TEXT        NOT NULL,
    categoria     VARCHAR(20) NOT NULL DEFAULT 'OUTROS',
    ordem         INTEGER     NOT NULL DEFAULT 0,
    ativa         BOOLEAN     NOT NULL DEFAULT TRUE,
    condominio_id BIGINT      NOT NULL REFERENCES condominios (id),
    created_at    TIMESTAMP   NOT NULL,
    updated_at    TIMESTAMP   NOT NULL
);
CREATE INDEX idx_faqs_condominio ON faqs (condominio_id);

CREATE TABLE notificacoes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo       VARCHAR(20)  NOT NULL,
    status     VARCHAR(20)  NOT NULL DEFAULT 'PENDENTE',
    assunto    VARCHAR(255),
    conteudo   TEXT         NOT NULL,
    enviado_em TIMESTAMP,
    erro       TEXT,
    usuario_id BIGINT       NOT NULL REFERENCES usuarios (id),
    created_at TIMESTAMP    NOT NULL
);
CREATE INDEX idx_notificacoes_usuario ON notificacoes (usuario_id);

CREATE TABLE preferencias_notificacao (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notificar_email    BOOLEAN   NOT NULL DEFAULT TRUE,
    notificar_whatsapp BOOLEAN   NOT NULL DEFAULT FALSE,
    usuario_id         BIGINT    NOT NULL UNIQUE REFERENCES usuarios (id),
    created_at         TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP NOT NULL
);
